apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-fail
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: In
            values:
            - salar
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:2.0
