apiVersion: apps/v1
kind: Deployment
metadata:
  name: podaffinity
spec:
  replicas: 4
  selector:
    matchLabels:
      name: devops
  template:
    metadata:
      name: with-pod-affinity-both
      labels:
        name: devops
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - devops
            topologyKey: kubernetes.io/hostname
      containers:
      - name: with-pod-affinity
        image: nginx

