apiVersion: v1 
kind: Pod
metadata:
  name: grafana-memory
  namespace: dev
  labels:
    type: monitoring
spec:
  containers:
  - name: grafana-container
    image: grafana/grafana:10.1.10
    ports:
    - containerPort: 3000
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 500Mi
        cpu: 150m

