apiVersion: v1
kind: Service
metadata:
  name: grafana-svc-nodeport-2
spec:
  selector:
    tier: web
  type: NodePort
  ports:
  - name: grafana-http
    port: 3000
    targetPort: 3000
    nodePort: 8080
