apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test-recreate 
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      type: deploy
  template:
    metadata:
      name: grafana
      labels:
        type: deploy
        tier: web
    spec:
      containers:
      - name: grafana-container
        image: grafana/grafana:main
        ports:
        - containerPort: 3000
