apiVersion: v1 
kind: Pod
metadata:
  name: grafana
  namespace: dev
  labels:
    type: monitoring
spec:
  containers:
  - name: grafana-container
    image: grafana/grafana:10.1.10
    ports:
    - containerPort: 3000
